/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tenew;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel
 */
public class jIntFrmEditCustomerDetails extends javax.swing.JInternalFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pstmt = null;
    ResultSet rs1 = null;
    Statement stmt = null;
    String query = null;
    int cust_no = 0;
    int type_no = 0, i = 0;
    String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
    String[] typename;
    String text;

    public jIntFrmEditCustomerDetails() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(jRBtnCasual);
        group.add(jRBtnPrivilege);
        jRBtnCasual.setSelected(true);
        jtxtName1.setEditable(false);
        jtxtPhone1.setEditable(false);
        jdteDOB1.setEnabled(false);
        jtxtEmail1.setEditable(false);
        jbtnEdit.setVisible(true);
        jbtnSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtSearch = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtxtName1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jdteDOB1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jtxtPhone1 = new javax.swing.JTextField();
        jtxtEmail1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jbtnSave = new javax.swing.JButton();
        jRBtnCasual = new javax.swing.JRadioButton();
        jRBtnPrivilege = new javax.swing.JRadioButton();
        jbtnEdit = new javax.swing.JButton();

        setClosable(true);
        setTitle("EDIT CUSTOMER DETAILS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("SEARCH");

        jtxtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchActionPerformed(evt);
            }
        });
        jtxtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtSearchKeyPressed(evt);
            }
        });

        jbtnSearch.setText("SEARCH");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jLabel9.setText("NAME");

        jtxtName1.setEditable(false);
        jtxtName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtName1KeyPressed(evt);
            }
        });

        jLabel10.setText("DOB");

        jdteDOB1.setEnabled(false);

        jLabel11.setText("PHONE");

        jtxtPhone1.setEditable(false);
        jtxtPhone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPhone1KeyPressed(evt);
            }
        });

        jtxtEmail1.setEditable(false);
        jtxtEmail1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtEmail1KeyPressed(evt);
            }
        });

        jLabel14.setText("EMAIL");

        jbtnSave.setText("SAVE");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jRBtnCasual.setText("CASUAL");

        jRBtnPrivilege.setText("PRIVILEGE");

        jbtnEdit.setText("EDIT");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jbtnEdit))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdteDOB1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jbtnSearch))
                                    .addComponent(jtxtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRBtnCasual)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBtnPrivilege))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnSave)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtnCasual)
                    .addComponent(jRBtnPrivilege))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jdteDOB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtxtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSave)
                    .addComponent(jbtnEdit))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchActionPerformed

    private void jtxtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchKeyPressed
        text = jtxtSearch.getText();
        if (text.length() == 15) {
            jtxtSearch.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtSearch.setEditable(true);
            }
        } else {
            jtxtSearch.setEditable(true);
        }
    }//GEN-LAST:event_jtxtSearchKeyPressed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed

        try {
            if (jRBtnCasual.isSelected()) {
                query = "select CUSTOMER_NO,NAME,DOB,PHONE,EMAIL,TYPE_NO from mst_customer where PHONE = ? and type_no = (select type_no from mst_type where type != 'PRIVILEGE' and flag!='D') and flag!='D'";
            } else if (jRBtnPrivilege.isSelected()) {
                query = "select CUSTOMER_NO,NAME,DOB,PHONE,EMAIL,TYPE_NO,BR_NO from mst_customer where BR_NO = ? and flag!='D'";
            }
            if (jtxtSearch.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter a search parameter!", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                con = new DBConnection().connect();
                pstmt = con.prepareStatement(query);
                pstmt.setString(1, jtxtSearch.getText().trim());
                rs = pstmt.executeQuery();
                if (rs.next()) {
                    cust_no = rs.getInt(1);
                    jtxtName1.setText(rs.getString(2));
                    jdteDOB1.setDate(rs.getDate(3));
                    jtxtPhone1.setText(rs.getString(4));
                    jtxtEmail1.setText(rs.getString(5));
                } else {
                    JOptionPane.showMessageDialog(this, "Does not exist!", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(jIntFrmMainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        if (jtxtName1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please make a search!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtPhone1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a phone number!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtEmail1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter email id", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jdteDOB1.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select DOB!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                con = new DBConnection().connect();
                con.setAutoCommit(false);
                query = "UPDATE mst_customer set name=?,email=?,phone=?,dob=?,FLAG = 'U' ,DATE_UPDATED = ?  where customer_no = ?";
                pstmt = con.prepareStatement(query);
                pstmt.setString(1, jtxtName1.getText().trim());
                pstmt.setString(2, jtxtEmail1.getText().trim());
                pstmt.setString(3, jtxtPhone1.getText().trim());
                pstmt.setString(4, new SimpleDateFormat("yyyy-MM-dd").format(jdteDOB1.getDate()));
                pstmt.setString(5, today);
                pstmt.setInt(6, cust_no);
                i = pstmt.executeUpdate();
                if (i > 0) {
                    con.commit();
                    JOptionPane.showMessageDialog(this, "Upgrade successful", "Info", JOptionPane.INFORMATION_MESSAGE);
                    clear1();
                    jRBtnCasual.setSelected(true);
                    jtxtName1.setEditable(false);
                    jtxtPhone1.setEditable(false);
                    jdteDOB1.setEnabled(false);
                    jtxtEmail1.setEditable(false);
                    jbtnEdit.setVisible(true);
                    jbtnSave.setVisible(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(jIntFrmConvert.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnSaveActionPerformed
    private void clear1() {
        jtxtSearch.setText("");
        jtxtName1.setText("");
        jtxtPhone1.setText("");
        jtxtEmail1.setText("");
        jdteDOB1.setDate(new Date());
    }
    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed

        if (jtxtName1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please make a search!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            jtxtName1.setEditable(true);
            jtxtPhone1.setEditable(true);
            jdteDOB1.setEnabled(true);
            jtxtEmail1.setEditable(true);
            jbtnEdit.setVisible(false);
            jbtnSave.setVisible(true);
        }

    }//GEN-LAST:event_jbtnEditActionPerformed

    private void jtxtName1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtName1KeyPressed
        text = jtxtName1.getText();
        if (text.length() == 50) {
            jtxtName1.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtName1.setEditable(true);
            }
        } else {
            jtxtName1.setEditable(true);
        }
    }//GEN-LAST:event_jtxtName1KeyPressed

    private void jtxtPhone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPhone1KeyPressed
        text = "";
        text = jtxtPhone1.getText();
        if (text.length() == 10) {
            jtxtPhone1.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtPhone1.setEditable(true);
            }
        } else if (evt.getKeyChar() >= evt.VK_0 && evt.getKeyChar() <= evt.VK_9 || evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
            jtxtPhone1.setEditable(true);
        } else {
            jtxtPhone1.setEditable(false);
        }
    }//GEN-LAST:event_jtxtPhone1KeyPressed

    private void jtxtEmail1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmail1KeyPressed
        text = jtxtEmail1.getText();
        if (text.length() == 40) {
            jtxtEmail1.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtEmail1.setEditable(true);
            }
        } else {
            jtxtEmail1.setEditable(true);
        }
    }//GEN-LAST:event_jtxtEmail1KeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBtnCasual;
    private javax.swing.JRadioButton jRBtnPrivilege;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnSearch;
    private com.toedter.calendar.JDateChooser jdteDOB1;
    private javax.swing.JTextField jtxtEmail1;
    private javax.swing.JTextField jtxtName1;
    private javax.swing.JTextField jtxtPhone1;
    private javax.swing.JTextField jtxtSearch;
    // End of variables declaration//GEN-END:variables
}
