/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tenew;

import javax.swing.ButtonGroup;

/**
 *
 * @author Joel
 */
public class jIntFrmUpdateOnOff extends javax.swing.JInternalFrame {

    /**
     * Creates new form jIntFrmUpdateOnOff
     */
    public jIntFrmUpdateOnOff() {
        initComponents();
        ButtonGroup btngrp = new ButtonGroup();
        btngrp.add(rbtnOn);
        btngrp.add(rbtnOff);
        if (Global.update) {
            rbtnOn.setSelected(true);
        } else {
            rbtnOff.setSelected(true);
        }
        System.out.println(Global.update);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnOn = new javax.swing.JRadioButton();
        rbtnOff = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("TURN ON/OFF UPDATE");

        rbtnOn.setText("ON");
        rbtnOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOnActionPerformed(evt);
            }
        });

        rbtnOff.setText("OFF");
        rbtnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(rbtnOn)
                .addGap(18, 18, 18)
                .addComponent(rbtnOff)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnOn)
                    .addComponent(rbtnOff))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOnActionPerformed
        Global.update = true;
        System.out.println(Global.update);
    }//GEN-LAST:event_rbtnOnActionPerformed

    private void rbtnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOffActionPerformed
        Global.update = false;
        System.out.println(Global.update);
    }//GEN-LAST:event_rbtnOffActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton rbtnOff;
    private javax.swing.JRadioButton rbtnOn;
    // End of variables declaration//GEN-END:variables
}
