/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tenew;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel
 */
public class jIntFrmTax extends javax.swing.JInternalFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pstmt = null;
    Statement stmt = null;
    String query = null;
    String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
    int i = 0;

    public jIntFrmTax() {
        try {
            initComponents();
            con = new DBConnection().connect();
            query = "select TAX from mst_tax where flag != 'D'";
            stmt = con.createStatement();
            rs = stmt.executeQuery(query);
            if (rs.next()) {
                jtxtTax.setText(rs.getString(1));
            } else {
                JOptionPane.showMessageDialog(this, "Please contact your admin, tax field is missing!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            jbtnEdit.setVisible(true);
            jbtnSave.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(jIntFrmTax.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JTextField();
        jbtnEdit = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();

        setClosable(true);
        setTitle("TAX EDITOR");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("ENTERTAINMENT TAX");

        jtxtTax.setEditable(false);

        jbtnEdit.setText("EDIT");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnSave.setText("SAVE");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbtnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEdit)
                    .addComponent(jbtnSave))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        jtxtTax.setEditable(true);
        jbtnEdit.setVisible(false);
        jbtnSave.setVisible(true);
    }//GEN-LAST:event_jbtnEditActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        if (jtxtTax.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select tax", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                i = 0;
                con = new DBConnection().connect();
                con.setAutoCommit(false);
                query = "UPDATE mst_tax set tax = ?,FLAG=?,DATE_UPDATED = ? where TAX_NO = 1";
                pstmt = con.prepareStatement(query);
                pstmt.setString(1, jtxtTax.getText().trim());
                pstmt.setString(2, "U");
                pstmt.setString(3, today);
                i = pstmt.executeUpdate();
                if (i > 0) {
                    con.commit();
                    JOptionPane.showMessageDialog(this, "Updated Successfully!", "Info", JOptionPane.INFORMATION_MESSAGE);                    
                    jtxtTax.setEditable(false);
                    jbtnEdit.setVisible(true);
                    jbtnSave.setVisible(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(jIntFrmTax.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JTextField jtxtTax;
    // End of variables declaration//GEN-END:variables
}
