/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tenew;

import java.awt.BorderLayout;
import java.awt.Container;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Joel
 */
public class jIntfrmReportViewer extends javax.swing.JInternalFrame {

    /**
     * Creates new form jIntfrmReportViewer
     */
    Connection con;
    public jIntfrmReportViewer() {
        initComponents();
    }
    public jIntfrmReportViewer(String filename) {
        this(filename, null);
    }

    public jIntfrmReportViewer(String filename, HashMap param) {
        try {
            System.out.println(filename);
            initComponents();
            con = new DBConnection().connect();
            JasperReport jasperReport = JasperCompileManager.compileReport(filename);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param, con);
            JRViewer viewer = new JRViewer(jasperPrint);
            Container container = getContentPane();
            container.setLayout(new BorderLayout());
            container.add(viewer);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                if(!con.isClosed()){
                    con.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
