/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tenew;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel
 */
public class jIntFrmConvert extends javax.swing.JInternalFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pstmt = null;
    ResultSet rs1 = null;
    Statement stmt = null;
    String query = null;
    int cust_no = 0;
    int type_no = 0, i = 0;
    String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
    String[] typename;
    String text;

    public jIntFrmConvert() {
        try {
            initComponents();
            con = new DBConnection().connect();
            query = "select TYPE_NO,NAME from MST_TYPE where flag != 'D' and type = 'PRIVILEGE'";
            pstmt = con.prepareStatement(query);
            rs = pstmt.executeQuery();
            jcmbType.addItem("");
            while (rs.next()) {
                jcmbType.addItem(rs.getString(1) + "   " + rs.getString(2));
            }
            ButtonGroup group = new ButtonGroup();
            group.add(jRBtnCasual);
            group.add(jRBtnPrivilege);
            jRBtnCasual.setSelected(true);
        } catch (SQLException ex) {
            Logger.getLogger(jIntFrmConvert.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtSearch = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtxtName1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jdteDOB1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jtxtPhone1 = new javax.swing.JTextField();
        jtxtEmail1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jlblCode = new javax.swing.JLabel();
        jtxtBRCode = new javax.swing.JTextField();
        jlblCredit = new javax.swing.JLabel();
        jtxtCredit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcmbType = new javax.swing.JComboBox();
        jRBtnCasual = new javax.swing.JRadioButton();
        jRBtnPrivilege = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("UPGRADE");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("SEARCH");

        jtxtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchActionPerformed(evt);
            }
        });
        jtxtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtSearchKeyPressed(evt);
            }
        });

        jbtnSearch.setText("SEARCH");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jLabel9.setText("NAME");

        jtxtName1.setEditable(false);

        jLabel10.setText("DOB");

        jdteDOB1.setEnabled(false);

        jLabel11.setText("PHONE");

        jtxtPhone1.setEditable(false);

        jtxtEmail1.setEditable(false);

        jLabel14.setText("EMAIL");

        jlblCode.setText("CODE");

        jtxtBRCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtBRCodeKeyPressed(evt);
            }
        });

        jlblCredit.setText("STORE CREDIT");

        jtxtCredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCreditKeyPressed(evt);
            }
        });

        jButton1.setText("UPGRADE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("TYPE");

        jRBtnCasual.setText("CASUAL");

        jRBtnPrivilege.setText("PRIVILEGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jlblCode)
                            .addComponent(jlblCredit)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdteDOB1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jtxtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(jbtnSearch)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRBtnCasual)
                                .addGap(18, 18, 18)
                                .addComponent(jRBtnPrivilege))
                            .addComponent(jcmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxtBRCode, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtEmail1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtnCasual)
                    .addComponent(jRBtnPrivilege))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jdteDOB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtxtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCode)
                    .addComponent(jtxtBRCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblCredit)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        try {
            if (jRBtnCasual.isSelected()) {
                query = "select CUSTOMER_NO,NAME,DOB,PHONE,EMAIL,TYPE_NO from mst_customer where PHONE = ? and type_no = (select type_no from mst_type where type != 'PRIVILEGE' and flag!='D') and flag!='D'";
            } else if (jRBtnPrivilege.isSelected()) {
                query = "select CUSTOMER_NO,NAME,DOB,PHONE,EMAIL,TYPE_NO,BR_NO from mst_customer where BR_NO = ? and flag!='D'";
            }
            if (jtxtSearch.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter a search parameter!", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                con = new DBConnection().connect();
                pstmt = con.prepareStatement(query);
                pstmt.setString(1, jtxtSearch.getText().trim());
                rs = pstmt.executeQuery();
                if (rs.next()) {
                    cust_no = rs.getInt(1);
                    jtxtName1.setText(rs.getString(2));
                    jdteDOB1.setDate(rs.getDate(3));
                    jtxtPhone1.setText(rs.getString(4));
                    jtxtEmail1.setText(rs.getString(5));
                    if (jRBtnPrivilege.isSelected()) {
                        jtxtBRCode.setText(rs.getString(7));
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Does not exist!", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(jIntFrmMainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbtnSearchActionPerformed
    private void clear1() {
        jtxtBRCode.setText("");
        jtxtSearch.setText("");
        jtxtName1.setText("");
        jtxtPhone1.setText("");
        jtxtEmail1.setText("");
        jdteDOB1.setDate(new Date());
        jtxtCredit.setText("");
        jcmbType.setSelectedItem("");
    }
    private void jtxtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jtxtName1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select a user!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtBRCode.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a BR code!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jtxtCredit.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter credit amount!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else if (jcmbType.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select type!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                con = new DBConnection().connect();
                con.setAutoCommit(false);
                typename = jcmbType.getSelectedItem().toString().split("   ");
                query = "UPDATE mst_customer set BR_NO = ? ,TYPE_NO = ? ,FLAG = 'I' ,DATE_UPDATED = ?,MEMBERSHIP_DATE = ?  where customer_no = ?";
                pstmt = con.prepareStatement(query);
                pstmt.setString(1, jtxtBRCode.getText().trim());
                pstmt.setString(2, typename[0]);
                pstmt.setString(3, today);
                pstmt.setString(4, today);
                pstmt.setInt(5, cust_no);
                i = pstmt.executeUpdate();

                query = "INSERT INTO trn_account(CUSTOMER_NO,DATE,AMOUNT,FLAG,DATE_CREATED) VALUES (?,?,?,?,?)";
                pstmt = con.prepareStatement(query);
                pstmt.setInt(1, cust_no);
                pstmt.setString(2, today);
                pstmt.setDouble(3, Double.valueOf(jtxtCredit.getText().trim()));
                pstmt.setString(4, "I");
                pstmt.setString(5, today);
                i = i + pstmt.executeUpdate();
                if (i > 1) {
                    con.commit();
                    JOptionPane.showMessageDialog(this, "Upgrade successful", "Info", JOptionPane.INFORMATION_MESSAGE);
                    clear1();
                }
            } catch (SQLException ex) {
                Logger.getLogger(jIntFrmConvert.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchKeyPressed
        text = jtxtSearch.getText();
        if (text.length() == 15) {
            jtxtSearch.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtSearch.setEditable(true);
            }
        } else {
            jtxtSearch.setEditable(true);
        }
    }//GEN-LAST:event_jtxtSearchKeyPressed

    private void jtxtCreditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCreditKeyPressed
        text = "";
        text = jtxtCredit.getText();
        if (text.length() == 8) {
            jtxtCredit.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtCredit.setEditable(true);
            }
        } else if (evt.getKeyChar() >= evt.VK_0 && evt.getKeyChar() <= evt.VK_9 || evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
            jtxtCredit.setEditable(true);
        } else {
            jtxtCredit.setEditable(false);
        }
    }//GEN-LAST:event_jtxtCreditKeyPressed

    private void jtxtBRCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBRCodeKeyPressed
        text = jtxtBRCode.getText();
        if (text.length() == 15) {
            jtxtBRCode.setEditable(false);
            if (evt.getKeyChar() == evt.VK_BACK_SPACE || evt.getKeyChar() == evt.VK_DELETE || evt.getKeyChar() == evt.VK_LEFT || evt.getKeyChar() == evt.VK_RIGHT) {
                jtxtBRCode.setEditable(true);
            }
        } else {
            jtxtBRCode.setEditable(true);
        }
    }//GEN-LAST:event_jtxtBRCodeKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBtnCasual;
    private javax.swing.JRadioButton jRBtnPrivilege;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JComboBox jcmbType;
    private com.toedter.calendar.JDateChooser jdteDOB1;
    private javax.swing.JLabel jlblCode;
    private javax.swing.JLabel jlblCredit;
    private javax.swing.JTextField jtxtBRCode;
    private javax.swing.JTextField jtxtCredit;
    private javax.swing.JTextField jtxtEmail1;
    private javax.swing.JTextField jtxtName1;
    private javax.swing.JTextField jtxtPhone1;
    private javax.swing.JTextField jtxtSearch;
    // End of variables declaration//GEN-END:variables
}
