/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tenew;

import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Joel
 */
public class jIntFrmCustomerSearch extends javax.swing.JInternalFrame {

    /**
     * Creates new form jIntFrmCustomerSearch
     */
    String projectpath;

    public jIntFrmCustomerSearch() {
        initComponents();
        try {
            projectpath = new File(".").getCanonicalPath();
        } catch (IOException ex) {
            Logger.getLogger(jIntFrmCustomerSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jcmbParameter = new javax.swing.JComboBox();
        jtxtSearch = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();

        setClosable(true);
        setTitle("Customer Search");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Parameter");

        jcmbParameter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Phone", "Name", "All" }));

        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jcmbParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnSearch)
                        .addGap(0, 258, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        if (jcmbParameter.getSelectedItem().equals("Phone")) {
            try {
                HashMap Param = new HashMap();
                Param.put("phno", "%" + jtxtSearch.getText().trim() + "%");
                jIntfrmReportViewer viewer = new jIntfrmReportViewer(projectpath + "/CustomerSearch.jrxml", Param);
                jDesktopPane1.removeAll();
                jDesktopPane1.add(viewer);
                viewer.setVisible(true);
                viewer.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(jIntFrmCustomerSearch.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jcmbParameter.getSelectedItem().equals("Name")) {
            try {
                HashMap Param = new HashMap();
                Param.put("name", "%" + jtxtSearch.getText().trim() + "%");
                jIntfrmReportViewer viewer = new jIntfrmReportViewer(projectpath + "/CustomerSearchName.jrxml", Param);
                jDesktopPane1.removeAll();
                jDesktopPane1.add(viewer);
                viewer.setVisible(true);
                viewer.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(jIntFrmCustomerSearch.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (jcmbParameter.getSelectedItem().equals("All")) {
            try {                
                jIntfrmReportViewer viewer = new jIntfrmReportViewer(projectpath + "/CustomerSearchAll.jrxml");
                jDesktopPane1.removeAll();
                jDesktopPane1.add(viewer);
                viewer.setVisible(true);
                viewer.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(jIntFrmCustomerSearch.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtnSearchActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JComboBox jcmbParameter;
    private javax.swing.JTextField jtxtSearch;
    // End of variables declaration//GEN-END:variables
}
